metadata.format.version = "1.1"

[versions]

jetbrains = "26.0.1"
ignite = "1.1.0"
mixin = "0.8.7"
mixinExtras = "0.4.1"
paperweight = "2.0.0-beta.13"
shadow = "8.1.1"
spotless = "6.25.0"
paper = "1.21.4-R0.1-SNAPSHOT"

[libraries]
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains" }

ignite = { group = "space.vectrix.ignite", name = "ignite-api", version.ref = "ignite" }
mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
mixinExtras = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixinExtras" }

build-paperweight = { module = "io.papermc.paperweight.userdev:io.papermc.paperweight.userdev.gradle.plugin", version.ref = "paperweight" }
build-shadow = { module = "com.github.johnrengelman:shadow", version.ref = "shadow" }
build-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
